// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/rodericusifo/fasttech-skill-test/mini-app/pkg/core/cart/controller"
	"github.com/rodericusifo/fasttech-skill-test/mini-app/pkg/core/cart/resource"
	"github.com/rodericusifo/fasttech-skill-test/mini-app/pkg/core/cart/service"
)

// Injectors from wire.go:

func CartController() *controller_cart.CartController {
	iCartResource := resource_cart.InitCartResource()
	iCartService := service_cart.InitCartService(iCartResource)
	cartController := controller_cart.InitCartController(iCartService)
	return cartController
}
