// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRequest is an autogenerated mock type for the IRequest type
type IRequest struct {
	mock.Mock
}

// CustomValidate provides a mock function with given fields:
func (_m *IRequest) CustomValidate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRequest creates a new instance of IRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRequest(t mockConstructorTestingTNewIRequest) *IRequest {
	mock := &IRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
